### ISSUE TITLE
nextcloud    openldap

### ISSUE THREAD

**Issue by 1551462073** [truenas/nss-pam-ldapd#2]
![image](https://user-images.githubusercontent.com/57369871/134231768-3dcc7906-bc48-4627-93bc-ae54d1152144.png)

Using the nextcloud of truenas, I found that I could not connect to the LDAP server when configuring LDAP integration

**Comment by 1551462073** [comment]
Can you help me? Thank you

**Comment by anodos325** [comment]
The correct avenue for support from community for TrueNAS is on our community forums: https://www.truenas.com/community/
